import About from "@/components/About/About";
import Archive from "@/components/Archive/Archive";
import Client from "@/components/Client/Client";
import Contact from "@/components/Contact/Contact";
import Cookie from "@/components/Cookie/Cookie";
import Footer from "@/components/Footer/Footer";
import Services from "@/components/Services/Services";
import Showreel from "@/components/Showreel/Showreel";
import Work from "@/components/Work/WorkCopy";
import Hero from "@/components/Hero/Hero";
import Head from "next/head";
import Elements from "@/components/Elements/Elements";

export default function Home() {
  return (
    <>
      <Elements />
      <Head>
        <title>Philippe Layani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Showreel />
      <Work />
      <Archive />
      <Client />
      <Services />
      <About />
      <Contact />
      <Footer />
      <Cookie />
    </>
  );
}
