import Footer from "@/components/Footer/Footer";
import ContentSection from "@/components/innerpage/ContentSection/ContentSection";
import HeadingSection from "@/components/innerpage/HeadingSection/HeadingSection";
import ImageSection from "@/components/innerpage/ImageSection/ImageSection";
import InnerHero from "@/components/innerpage/InnerHero/InnerHero";
import MobileSection from "@/components/innerpage/MobileSection/MobileSection";
import SubHeading from "@/components/innerpage/SubHeading/SubHeading";
import VideoSection from "@/components/innerpage/VideoSection/VideoSection";
import Wrapper from "@/components/innerpage/Wrapper/Wrapper";
import Head from "next/head";

export default function Index() {
  return (
    <>
      <Head>
        <title>Myndyoga - Philippe Layani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <InnerHero heading={["Myndyoga"]} />
        <SubHeading
          subHeading={
            "Welcome to Myndyoga, the ultimate destination for anyone looking for stunning and high-quality Bauhaus wallpaper. The website has been designed to provide a seamless and enjoyable shopping experience."
          }
        />
        <ContentSection
          logo={"/work/myndyoga/logo.png"}
          description={[
            "TBA 21 is deeply committed to raising awareness about the urgent environmental challenges facing our planet through innovative and thought-provoking art. The redesign aimed to create a digital platform that reflects the organization's visionary work, while offering an immersive and engaging experience for visitors. ",
            "MONIPOL offers a complete range of clinical development and consulting services to a strong customer base of primarily small and mid-size pharmaceutical, biotechnology, and medical device companies.",
          ]}
          image={"/work/myndyoga/img1.jpg"}
        />
        <VideoSection video="" poster="/work/myndyoga/poster.jpg" />
        <ImageSection image="/work/myndyoga/webpage1.jpg" />
        <HeadingSection
          heading="Lorem ipsum dolor sit amet Lorem ipsum dolor sit ametLorem ipsum dolor sit ametLorem ipsum dolor sit amet"
          image="/work/myndyoga/headingImage1.png"
        />
        <ContentSection
          type=""
          description={[
            "The Bauhaus wallpaper collection captures the spirit of the movement, with its clean lines, bold shapes, and striking colors. Each design in the collection is a modern interpretation of the classic Bauhaus style, featuring geometric shapes and abstract patterns that reflect the movement’s commitment to simplicity and functionality.",
            "The wallpaper is available in a range of colors and patterns, from monochromatic designs to bold and colorful compositions that make a statement. Whether you’re looking for a subtle accent wall or a bold statement piece, there is a Bauhaus wallpaper design that will suit your needs.",
          ]}
          image={"/work/myndyoga/img2.jpg"}
          minDescription
          leftImg
        />
        <ImageSection
          image="/work/myndyoga/webpage2.jpg"
          type="withBg"
          backgroundImage={"/work/myndyoga/webpageBg.jpg"}
        />
        <SubHeading
          subHeading={
            "Welcome to Bauhaustapete, the ultimate destination for anyone looking for stunning and high-quality Bauhaus wallpaper. The website has been designed to provide a seamless and enjoyable shopping experience."
          }
        />
        <ContentSection
          type=""
          description={[
            "The Bauhaus wallpaper collection captures the spirit of the movement, with its clean lines, bold shapes, and striking colors. Each design in the collection is a modern interpretation of the classic Bauhaus style, featuring geometric shapes and abstract patterns that reflect the movement’s commitment to simplicity and functionality.",
            "The wallpaper is available in a range of colors and patterns, from monochromatic designs to bold and colorful compositions that make a statement. Whether you’re looking for a subtle accent wall or a bold statement piece, there is a Bauhaus wallpaper design that will suit your needs.",
          ]}
          image={"/work/myndyoga/img3.jpg"}
          minDescription
        />
        <ImageSection image="/work/myndyoga/webpage3.jpg" type="fullImg" />
        <MobileSection
          images={[
            "/work/myndyoga/mobile1.png",
            "/work/myndyoga/mobile2.png",
          ]}
        />
        <ImageSection
          doubleImg={["/work/myndyoga/img4.jpg", "/work/myndyoga/img5.jpg"]}
          type="doubleImg"
        />
        <ImageSection image="/work/myndyoga/fullweb1.jpg" />
        <HeadingSection
          heading="Lorem ipsum dolor sit amet Lorem ipsum dolor sit ametLorem ipsum dolor sit ametLorem ipsum dolor sit amet"
          image="/work/myndyoga/headingImage2.png"
        />
      </Wrapper>
      <Footer />
    </>
  );
}
